export const event = {
  id: true,
  status: true,
  betsCloseTime: true,
  creatorId: true,
  poolAboveEq: true,
  poolBelow: true,
  totalBetsAmount: true,
  totalLiquidityProvided: true,
  totalLiquidityShares: true,
  totalValueLocked: true,
  liquidityPercent: true,
  measurePeriod: true,
  closedOracleTime: true,
  createdTime: true,
  startRate: true,
  closedRa